// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: remind/v1/remind.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Remind.V1 {
  public static partial class RemindService
  {
    static readonly string __ServiceName = "remind.v1.RemindService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.GetRemindRequest> __Marshaller_remind_v1_GetRemindRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.GetRemindRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.GetRemindResponse> __Marshaller_remind_v1_GetRemindResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.GetRemindResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.GetRemindsRequest> __Marshaller_remind_v1_GetRemindsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.GetRemindsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.GetRemindsResponse> __Marshaller_remind_v1_GetRemindsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.GetRemindsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.CreateRemindRequest> __Marshaller_remind_v1_CreateRemindRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.CreateRemindRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.CreateRemindResponse> __Marshaller_remind_v1_CreateRemindResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.CreateRemindResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.UpdateRemindRequest> __Marshaller_remind_v1_UpdateRemindRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.UpdateRemindRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.UpdateRemindResponse> __Marshaller_remind_v1_UpdateRemindResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.UpdateRemindResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.DeleteRemindRequest> __Marshaller_remind_v1_DeleteRemindRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.DeleteRemindRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.DeleteRemindResponse> __Marshaller_remind_v1_DeleteRemindResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.DeleteRemindResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Remind.V1.GetRemindRequest, global::Remind.V1.GetRemindResponse> __Method_GetRemind = new grpc::Method<global::Remind.V1.GetRemindRequest, global::Remind.V1.GetRemindResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRemind",
        __Marshaller_remind_v1_GetRemindRequest,
        __Marshaller_remind_v1_GetRemindResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Remind.V1.GetRemindsRequest, global::Remind.V1.GetRemindsResponse> __Method_GetReminds = new grpc::Method<global::Remind.V1.GetRemindsRequest, global::Remind.V1.GetRemindsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetReminds",
        __Marshaller_remind_v1_GetRemindsRequest,
        __Marshaller_remind_v1_GetRemindsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Remind.V1.CreateRemindRequest, global::Remind.V1.CreateRemindResponse> __Method_CreateRemind = new grpc::Method<global::Remind.V1.CreateRemindRequest, global::Remind.V1.CreateRemindResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateRemind",
        __Marshaller_remind_v1_CreateRemindRequest,
        __Marshaller_remind_v1_CreateRemindResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Remind.V1.UpdateRemindRequest, global::Remind.V1.UpdateRemindResponse> __Method_UpdateRemind = new grpc::Method<global::Remind.V1.UpdateRemindRequest, global::Remind.V1.UpdateRemindResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateRemind",
        __Marshaller_remind_v1_UpdateRemindRequest,
        __Marshaller_remind_v1_UpdateRemindResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Remind.V1.DeleteRemindRequest, global::Remind.V1.DeleteRemindResponse> __Method_DeleteRemind = new grpc::Method<global::Remind.V1.DeleteRemindRequest, global::Remind.V1.DeleteRemindResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteRemind",
        __Marshaller_remind_v1_DeleteRemindRequest,
        __Marshaller_remind_v1_DeleteRemindResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Remind.V1.RemindReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RemindService</summary>
    [grpc::BindServiceMethod(typeof(RemindService), "BindService")]
    public abstract partial class RemindServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Remind.V1.GetRemindResponse> GetRemind(global::Remind.V1.GetRemindRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Remind.V1.GetRemindsResponse> GetReminds(global::Remind.V1.GetRemindsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Remind.V1.CreateRemindResponse> CreateRemind(global::Remind.V1.CreateRemindRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Remind.V1.UpdateRemindResponse> UpdateRemind(global::Remind.V1.UpdateRemindRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Remind.V1.DeleteRemindResponse> DeleteRemind(global::Remind.V1.DeleteRemindRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RemindService</summary>
    public partial class RemindServiceClient : grpc::ClientBase<RemindServiceClient>
    {
      /// <summary>Creates a new client for RemindService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public RemindServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RemindService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public RemindServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected RemindServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected RemindServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.GetRemindResponse GetRemind(global::Remind.V1.GetRemindRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRemind(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.GetRemindResponse GetRemind(global::Remind.V1.GetRemindRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRemind, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.GetRemindResponse> GetRemindAsync(global::Remind.V1.GetRemindRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRemindAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.GetRemindResponse> GetRemindAsync(global::Remind.V1.GetRemindRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRemind, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.GetRemindsResponse GetReminds(global::Remind.V1.GetRemindsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetReminds(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.GetRemindsResponse GetReminds(global::Remind.V1.GetRemindsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetReminds, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.GetRemindsResponse> GetRemindsAsync(global::Remind.V1.GetRemindsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRemindsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.GetRemindsResponse> GetRemindsAsync(global::Remind.V1.GetRemindsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetReminds, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.CreateRemindResponse CreateRemind(global::Remind.V1.CreateRemindRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateRemind(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.CreateRemindResponse CreateRemind(global::Remind.V1.CreateRemindRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateRemind, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.CreateRemindResponse> CreateRemindAsync(global::Remind.V1.CreateRemindRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateRemindAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.CreateRemindResponse> CreateRemindAsync(global::Remind.V1.CreateRemindRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateRemind, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.UpdateRemindResponse UpdateRemind(global::Remind.V1.UpdateRemindRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateRemind(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.UpdateRemindResponse UpdateRemind(global::Remind.V1.UpdateRemindRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateRemind, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.UpdateRemindResponse> UpdateRemindAsync(global::Remind.V1.UpdateRemindRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateRemindAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.UpdateRemindResponse> UpdateRemindAsync(global::Remind.V1.UpdateRemindRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateRemind, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.DeleteRemindResponse DeleteRemind(global::Remind.V1.DeleteRemindRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteRemind(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.DeleteRemindResponse DeleteRemind(global::Remind.V1.DeleteRemindRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteRemind, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.DeleteRemindResponse> DeleteRemindAsync(global::Remind.V1.DeleteRemindRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteRemindAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.DeleteRemindResponse> DeleteRemindAsync(global::Remind.V1.DeleteRemindRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteRemind, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override RemindServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RemindServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(RemindServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetRemind, serviceImpl.GetRemind)
          .AddMethod(__Method_GetReminds, serviceImpl.GetReminds)
          .AddMethod(__Method_CreateRemind, serviceImpl.CreateRemind)
          .AddMethod(__Method_UpdateRemind, serviceImpl.UpdateRemind)
          .AddMethod(__Method_DeleteRemind, serviceImpl.DeleteRemind).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, RemindServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetRemind, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Remind.V1.GetRemindRequest, global::Remind.V1.GetRemindResponse>(serviceImpl.GetRemind));
      serviceBinder.AddMethod(__Method_GetReminds, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Remind.V1.GetRemindsRequest, global::Remind.V1.GetRemindsResponse>(serviceImpl.GetReminds));
      serviceBinder.AddMethod(__Method_CreateRemind, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Remind.V1.CreateRemindRequest, global::Remind.V1.CreateRemindResponse>(serviceImpl.CreateRemind));
      serviceBinder.AddMethod(__Method_UpdateRemind, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Remind.V1.UpdateRemindRequest, global::Remind.V1.UpdateRemindResponse>(serviceImpl.UpdateRemind));
      serviceBinder.AddMethod(__Method_DeleteRemind, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Remind.V1.DeleteRemindRequest, global::Remind.V1.DeleteRemindResponse>(serviceImpl.DeleteRemind));
    }

  }
}
#endregion
