// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: remind/v1/remind_group.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Remind.V1 {
  public static partial class RemindGroupService
  {
    static readonly string __ServiceName = "remind.v1.RemindGroupService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.GetRemindGroupRequest> __Marshaller_remind_v1_GetRemindGroupRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.GetRemindGroupRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.GetRemindGroupResponse> __Marshaller_remind_v1_GetRemindGroupResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.GetRemindGroupResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.GetRemindGroupsRequest> __Marshaller_remind_v1_GetRemindGroupsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.GetRemindGroupsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.GetRemindGroupsResponse> __Marshaller_remind_v1_GetRemindGroupsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.GetRemindGroupsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.CreateRemindGroupRequest> __Marshaller_remind_v1_CreateRemindGroupRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.CreateRemindGroupRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.CreateRemindGroupResponse> __Marshaller_remind_v1_CreateRemindGroupResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.CreateRemindGroupResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.UpdateRemindGroupRequest> __Marshaller_remind_v1_UpdateRemindGroupRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.UpdateRemindGroupRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.UpdateRemindGroupResponse> __Marshaller_remind_v1_UpdateRemindGroupResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.UpdateRemindGroupResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.DeleteRemindGroupRequest> __Marshaller_remind_v1_DeleteRemindGroupRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.DeleteRemindGroupRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Remind.V1.DeleteRemindGroupResponse> __Marshaller_remind_v1_DeleteRemindGroupResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Remind.V1.DeleteRemindGroupResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Remind.V1.GetRemindGroupRequest, global::Remind.V1.GetRemindGroupResponse> __Method_GetRemindGroup = new grpc::Method<global::Remind.V1.GetRemindGroupRequest, global::Remind.V1.GetRemindGroupResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRemindGroup",
        __Marshaller_remind_v1_GetRemindGroupRequest,
        __Marshaller_remind_v1_GetRemindGroupResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Remind.V1.GetRemindGroupsRequest, global::Remind.V1.GetRemindGroupsResponse> __Method_GetRemindGroups = new grpc::Method<global::Remind.V1.GetRemindGroupsRequest, global::Remind.V1.GetRemindGroupsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRemindGroups",
        __Marshaller_remind_v1_GetRemindGroupsRequest,
        __Marshaller_remind_v1_GetRemindGroupsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Remind.V1.CreateRemindGroupRequest, global::Remind.V1.CreateRemindGroupResponse> __Method_CreateRemindGroup = new grpc::Method<global::Remind.V1.CreateRemindGroupRequest, global::Remind.V1.CreateRemindGroupResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateRemindGroup",
        __Marshaller_remind_v1_CreateRemindGroupRequest,
        __Marshaller_remind_v1_CreateRemindGroupResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Remind.V1.UpdateRemindGroupRequest, global::Remind.V1.UpdateRemindGroupResponse> __Method_UpdateRemindGroup = new grpc::Method<global::Remind.V1.UpdateRemindGroupRequest, global::Remind.V1.UpdateRemindGroupResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateRemindGroup",
        __Marshaller_remind_v1_UpdateRemindGroupRequest,
        __Marshaller_remind_v1_UpdateRemindGroupResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Remind.V1.DeleteRemindGroupRequest, global::Remind.V1.DeleteRemindGroupResponse> __Method_DeleteRemindGroup = new grpc::Method<global::Remind.V1.DeleteRemindGroupRequest, global::Remind.V1.DeleteRemindGroupResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteRemindGroup",
        __Marshaller_remind_v1_DeleteRemindGroupRequest,
        __Marshaller_remind_v1_DeleteRemindGroupResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Remind.V1.RemindGroupReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RemindGroupService</summary>
    [grpc::BindServiceMethod(typeof(RemindGroupService), "BindService")]
    public abstract partial class RemindGroupServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Remind.V1.GetRemindGroupResponse> GetRemindGroup(global::Remind.V1.GetRemindGroupRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Remind.V1.GetRemindGroupsResponse> GetRemindGroups(global::Remind.V1.GetRemindGroupsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Remind.V1.CreateRemindGroupResponse> CreateRemindGroup(global::Remind.V1.CreateRemindGroupRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Remind.V1.UpdateRemindGroupResponse> UpdateRemindGroup(global::Remind.V1.UpdateRemindGroupRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Remind.V1.DeleteRemindGroupResponse> DeleteRemindGroup(global::Remind.V1.DeleteRemindGroupRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RemindGroupService</summary>
    public partial class RemindGroupServiceClient : grpc::ClientBase<RemindGroupServiceClient>
    {
      /// <summary>Creates a new client for RemindGroupService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public RemindGroupServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RemindGroupService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public RemindGroupServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected RemindGroupServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected RemindGroupServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.GetRemindGroupResponse GetRemindGroup(global::Remind.V1.GetRemindGroupRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRemindGroup(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.GetRemindGroupResponse GetRemindGroup(global::Remind.V1.GetRemindGroupRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRemindGroup, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.GetRemindGroupResponse> GetRemindGroupAsync(global::Remind.V1.GetRemindGroupRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRemindGroupAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.GetRemindGroupResponse> GetRemindGroupAsync(global::Remind.V1.GetRemindGroupRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRemindGroup, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.GetRemindGroupsResponse GetRemindGroups(global::Remind.V1.GetRemindGroupsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRemindGroups(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.GetRemindGroupsResponse GetRemindGroups(global::Remind.V1.GetRemindGroupsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRemindGroups, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.GetRemindGroupsResponse> GetRemindGroupsAsync(global::Remind.V1.GetRemindGroupsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRemindGroupsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.GetRemindGroupsResponse> GetRemindGroupsAsync(global::Remind.V1.GetRemindGroupsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRemindGroups, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.CreateRemindGroupResponse CreateRemindGroup(global::Remind.V1.CreateRemindGroupRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateRemindGroup(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.CreateRemindGroupResponse CreateRemindGroup(global::Remind.V1.CreateRemindGroupRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateRemindGroup, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.CreateRemindGroupResponse> CreateRemindGroupAsync(global::Remind.V1.CreateRemindGroupRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateRemindGroupAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.CreateRemindGroupResponse> CreateRemindGroupAsync(global::Remind.V1.CreateRemindGroupRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateRemindGroup, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.UpdateRemindGroupResponse UpdateRemindGroup(global::Remind.V1.UpdateRemindGroupRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateRemindGroup(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.UpdateRemindGroupResponse UpdateRemindGroup(global::Remind.V1.UpdateRemindGroupRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateRemindGroup, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.UpdateRemindGroupResponse> UpdateRemindGroupAsync(global::Remind.V1.UpdateRemindGroupRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateRemindGroupAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.UpdateRemindGroupResponse> UpdateRemindGroupAsync(global::Remind.V1.UpdateRemindGroupRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateRemindGroup, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.DeleteRemindGroupResponse DeleteRemindGroup(global::Remind.V1.DeleteRemindGroupRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteRemindGroup(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Remind.V1.DeleteRemindGroupResponse DeleteRemindGroup(global::Remind.V1.DeleteRemindGroupRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteRemindGroup, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.DeleteRemindGroupResponse> DeleteRemindGroupAsync(global::Remind.V1.DeleteRemindGroupRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteRemindGroupAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Remind.V1.DeleteRemindGroupResponse> DeleteRemindGroupAsync(global::Remind.V1.DeleteRemindGroupRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteRemindGroup, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override RemindGroupServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RemindGroupServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(RemindGroupServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetRemindGroup, serviceImpl.GetRemindGroup)
          .AddMethod(__Method_GetRemindGroups, serviceImpl.GetRemindGroups)
          .AddMethod(__Method_CreateRemindGroup, serviceImpl.CreateRemindGroup)
          .AddMethod(__Method_UpdateRemindGroup, serviceImpl.UpdateRemindGroup)
          .AddMethod(__Method_DeleteRemindGroup, serviceImpl.DeleteRemindGroup).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, RemindGroupServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetRemindGroup, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Remind.V1.GetRemindGroupRequest, global::Remind.V1.GetRemindGroupResponse>(serviceImpl.GetRemindGroup));
      serviceBinder.AddMethod(__Method_GetRemindGroups, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Remind.V1.GetRemindGroupsRequest, global::Remind.V1.GetRemindGroupsResponse>(serviceImpl.GetRemindGroups));
      serviceBinder.AddMethod(__Method_CreateRemindGroup, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Remind.V1.CreateRemindGroupRequest, global::Remind.V1.CreateRemindGroupResponse>(serviceImpl.CreateRemindGroup));
      serviceBinder.AddMethod(__Method_UpdateRemindGroup, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Remind.V1.UpdateRemindGroupRequest, global::Remind.V1.UpdateRemindGroupResponse>(serviceImpl.UpdateRemindGroup));
      serviceBinder.AddMethod(__Method_DeleteRemindGroup, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Remind.V1.DeleteRemindGroupRequest, global::Remind.V1.DeleteRemindGroupResponse>(serviceImpl.DeleteRemindGroup));
    }

  }
}
#endregion
