// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: remind_template/v1/remindtemplate.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace RemindTemplate.V1 {
  public static partial class RemindTemplateService
  {
    static readonly string __ServiceName = "remind_template.v1.RemindTemplateService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RemindTemplate.V1.GetRemindTemplateRequest> __Marshaller_remind_template_v1_GetRemindTemplateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RemindTemplate.V1.GetRemindTemplateRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RemindTemplate.V1.GetRemindTemplateResponse> __Marshaller_remind_template_v1_GetRemindTemplateResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RemindTemplate.V1.GetRemindTemplateResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RemindTemplate.V1.GetRemindTemplatesRequest> __Marshaller_remind_template_v1_GetRemindTemplatesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RemindTemplate.V1.GetRemindTemplatesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RemindTemplate.V1.GetRemindTemplatesResponse> __Marshaller_remind_template_v1_GetRemindTemplatesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RemindTemplate.V1.GetRemindTemplatesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RemindTemplate.V1.CreateRemindTemplateRequest> __Marshaller_remind_template_v1_CreateRemindTemplateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RemindTemplate.V1.CreateRemindTemplateRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RemindTemplate.V1.CreateRemindTemplateResponse> __Marshaller_remind_template_v1_CreateRemindTemplateResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RemindTemplate.V1.CreateRemindTemplateResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RemindTemplate.V1.UpdateRemindTemplateRequest> __Marshaller_remind_template_v1_UpdateRemindTemplateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RemindTemplate.V1.UpdateRemindTemplateRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RemindTemplate.V1.UpdateRemindTemplateResponse> __Marshaller_remind_template_v1_UpdateRemindTemplateResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RemindTemplate.V1.UpdateRemindTemplateResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RemindTemplate.V1.DeleteRemindTemplateRequest> __Marshaller_remind_template_v1_DeleteRemindTemplateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RemindTemplate.V1.DeleteRemindTemplateRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RemindTemplate.V1.DeleteRemindTemplateResponse> __Marshaller_remind_template_v1_DeleteRemindTemplateResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RemindTemplate.V1.DeleteRemindTemplateResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::RemindTemplate.V1.GetRemindTemplateRequest, global::RemindTemplate.V1.GetRemindTemplateResponse> __Method_GetRemindTemplate = new grpc::Method<global::RemindTemplate.V1.GetRemindTemplateRequest, global::RemindTemplate.V1.GetRemindTemplateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRemindTemplate",
        __Marshaller_remind_template_v1_GetRemindTemplateRequest,
        __Marshaller_remind_template_v1_GetRemindTemplateResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::RemindTemplate.V1.GetRemindTemplatesRequest, global::RemindTemplate.V1.GetRemindTemplatesResponse> __Method_GetRemindTemplates = new grpc::Method<global::RemindTemplate.V1.GetRemindTemplatesRequest, global::RemindTemplate.V1.GetRemindTemplatesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRemindTemplates",
        __Marshaller_remind_template_v1_GetRemindTemplatesRequest,
        __Marshaller_remind_template_v1_GetRemindTemplatesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::RemindTemplate.V1.CreateRemindTemplateRequest, global::RemindTemplate.V1.CreateRemindTemplateResponse> __Method_CreateRemindTemplate = new grpc::Method<global::RemindTemplate.V1.CreateRemindTemplateRequest, global::RemindTemplate.V1.CreateRemindTemplateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateRemindTemplate",
        __Marshaller_remind_template_v1_CreateRemindTemplateRequest,
        __Marshaller_remind_template_v1_CreateRemindTemplateResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::RemindTemplate.V1.UpdateRemindTemplateRequest, global::RemindTemplate.V1.UpdateRemindTemplateResponse> __Method_UpdateRemindTemplate = new grpc::Method<global::RemindTemplate.V1.UpdateRemindTemplateRequest, global::RemindTemplate.V1.UpdateRemindTemplateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateRemindTemplate",
        __Marshaller_remind_template_v1_UpdateRemindTemplateRequest,
        __Marshaller_remind_template_v1_UpdateRemindTemplateResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::RemindTemplate.V1.DeleteRemindTemplateRequest, global::RemindTemplate.V1.DeleteRemindTemplateResponse> __Method_DeleteRemindTemplate = new grpc::Method<global::RemindTemplate.V1.DeleteRemindTemplateRequest, global::RemindTemplate.V1.DeleteRemindTemplateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteRemindTemplate",
        __Marshaller_remind_template_v1_DeleteRemindTemplateRequest,
        __Marshaller_remind_template_v1_DeleteRemindTemplateResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::RemindTemplate.V1.RemindtemplateReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RemindTemplateService</summary>
    [grpc::BindServiceMethod(typeof(RemindTemplateService), "BindService")]
    public abstract partial class RemindTemplateServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::RemindTemplate.V1.GetRemindTemplateResponse> GetRemindTemplate(global::RemindTemplate.V1.GetRemindTemplateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::RemindTemplate.V1.GetRemindTemplatesResponse> GetRemindTemplates(global::RemindTemplate.V1.GetRemindTemplatesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::RemindTemplate.V1.CreateRemindTemplateResponse> CreateRemindTemplate(global::RemindTemplate.V1.CreateRemindTemplateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::RemindTemplate.V1.UpdateRemindTemplateResponse> UpdateRemindTemplate(global::RemindTemplate.V1.UpdateRemindTemplateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::RemindTemplate.V1.DeleteRemindTemplateResponse> DeleteRemindTemplate(global::RemindTemplate.V1.DeleteRemindTemplateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RemindTemplateService</summary>
    public partial class RemindTemplateServiceClient : grpc::ClientBase<RemindTemplateServiceClient>
    {
      /// <summary>Creates a new client for RemindTemplateService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public RemindTemplateServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RemindTemplateService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public RemindTemplateServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected RemindTemplateServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected RemindTemplateServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RemindTemplate.V1.GetRemindTemplateResponse GetRemindTemplate(global::RemindTemplate.V1.GetRemindTemplateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRemindTemplate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RemindTemplate.V1.GetRemindTemplateResponse GetRemindTemplate(global::RemindTemplate.V1.GetRemindTemplateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRemindTemplate, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RemindTemplate.V1.GetRemindTemplateResponse> GetRemindTemplateAsync(global::RemindTemplate.V1.GetRemindTemplateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRemindTemplateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RemindTemplate.V1.GetRemindTemplateResponse> GetRemindTemplateAsync(global::RemindTemplate.V1.GetRemindTemplateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRemindTemplate, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RemindTemplate.V1.GetRemindTemplatesResponse GetRemindTemplates(global::RemindTemplate.V1.GetRemindTemplatesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRemindTemplates(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RemindTemplate.V1.GetRemindTemplatesResponse GetRemindTemplates(global::RemindTemplate.V1.GetRemindTemplatesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRemindTemplates, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RemindTemplate.V1.GetRemindTemplatesResponse> GetRemindTemplatesAsync(global::RemindTemplate.V1.GetRemindTemplatesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRemindTemplatesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RemindTemplate.V1.GetRemindTemplatesResponse> GetRemindTemplatesAsync(global::RemindTemplate.V1.GetRemindTemplatesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRemindTemplates, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RemindTemplate.V1.CreateRemindTemplateResponse CreateRemindTemplate(global::RemindTemplate.V1.CreateRemindTemplateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateRemindTemplate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RemindTemplate.V1.CreateRemindTemplateResponse CreateRemindTemplate(global::RemindTemplate.V1.CreateRemindTemplateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateRemindTemplate, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RemindTemplate.V1.CreateRemindTemplateResponse> CreateRemindTemplateAsync(global::RemindTemplate.V1.CreateRemindTemplateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateRemindTemplateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RemindTemplate.V1.CreateRemindTemplateResponse> CreateRemindTemplateAsync(global::RemindTemplate.V1.CreateRemindTemplateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateRemindTemplate, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RemindTemplate.V1.UpdateRemindTemplateResponse UpdateRemindTemplate(global::RemindTemplate.V1.UpdateRemindTemplateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateRemindTemplate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RemindTemplate.V1.UpdateRemindTemplateResponse UpdateRemindTemplate(global::RemindTemplate.V1.UpdateRemindTemplateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateRemindTemplate, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RemindTemplate.V1.UpdateRemindTemplateResponse> UpdateRemindTemplateAsync(global::RemindTemplate.V1.UpdateRemindTemplateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateRemindTemplateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RemindTemplate.V1.UpdateRemindTemplateResponse> UpdateRemindTemplateAsync(global::RemindTemplate.V1.UpdateRemindTemplateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateRemindTemplate, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RemindTemplate.V1.DeleteRemindTemplateResponse DeleteRemindTemplate(global::RemindTemplate.V1.DeleteRemindTemplateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteRemindTemplate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RemindTemplate.V1.DeleteRemindTemplateResponse DeleteRemindTemplate(global::RemindTemplate.V1.DeleteRemindTemplateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteRemindTemplate, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RemindTemplate.V1.DeleteRemindTemplateResponse> DeleteRemindTemplateAsync(global::RemindTemplate.V1.DeleteRemindTemplateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteRemindTemplateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RemindTemplate.V1.DeleteRemindTemplateResponse> DeleteRemindTemplateAsync(global::RemindTemplate.V1.DeleteRemindTemplateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteRemindTemplate, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override RemindTemplateServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RemindTemplateServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(RemindTemplateServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetRemindTemplate, serviceImpl.GetRemindTemplate)
          .AddMethod(__Method_GetRemindTemplates, serviceImpl.GetRemindTemplates)
          .AddMethod(__Method_CreateRemindTemplate, serviceImpl.CreateRemindTemplate)
          .AddMethod(__Method_UpdateRemindTemplate, serviceImpl.UpdateRemindTemplate)
          .AddMethod(__Method_DeleteRemindTemplate, serviceImpl.DeleteRemindTemplate).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, RemindTemplateServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetRemindTemplate, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::RemindTemplate.V1.GetRemindTemplateRequest, global::RemindTemplate.V1.GetRemindTemplateResponse>(serviceImpl.GetRemindTemplate));
      serviceBinder.AddMethod(__Method_GetRemindTemplates, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::RemindTemplate.V1.GetRemindTemplatesRequest, global::RemindTemplate.V1.GetRemindTemplatesResponse>(serviceImpl.GetRemindTemplates));
      serviceBinder.AddMethod(__Method_CreateRemindTemplate, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::RemindTemplate.V1.CreateRemindTemplateRequest, global::RemindTemplate.V1.CreateRemindTemplateResponse>(serviceImpl.CreateRemindTemplate));
      serviceBinder.AddMethod(__Method_UpdateRemindTemplate, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::RemindTemplate.V1.UpdateRemindTemplateRequest, global::RemindTemplate.V1.UpdateRemindTemplateResponse>(serviceImpl.UpdateRemindTemplate));
      serviceBinder.AddMethod(__Method_DeleteRemindTemplate, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::RemindTemplate.V1.DeleteRemindTemplateRequest, global::RemindTemplate.V1.DeleteRemindTemplateResponse>(serviceImpl.DeleteRemindTemplate));
    }

  }
}
#endregion
